### ISSUE TITLE
Examples not working

### ISSUE THREAD

**Issue by ambition-consulting** [wll8/redoc-try#16]
So glad I found your project, I especially like your license model.

However, the examples seem to be broken. Is this something you could fix, or is it broken inside swagger-ui also?

![image](https://user-images.githubusercontent.com/4218334/126839543-c0ece9ab-b3e1-4a5b-8279-04b133e24cf7.png)

My spec is using external examples, which my unit tests also use to validate them automatically:

```
/yaya:
    post:
      summary: Non-blocking
      requestBody:
        content:
          application/json; charset=UTF-8:
            schema:
              $ref: '#/components/schemas/CoreRequest'
            examples:
              blik1:
                summary: BLIK1
                description: 'yaya1 '
                externalValue: ../blik1.json
              blik2:
                summary: BLIK2
                description: 'yaya2 '
                externalValue: ../blik2.json
```

**Comment by wll8** [comment]
Can you give me an openApi file that has removed sensitive information? Used to help me reproduce the problems you encountered so that I know how to fix them.

`or is it broken inside swagger-ui also?` You can just use swagger-ui to try it out.

**Comment by ambition-consulting** [comment]
I believe it stems from https://github.com/swagger-api/swagger-ui/issues/5433

**Comment by wll8** [comment]
It's better to be sure. If this problem can be reproduced by just using swagger-ui, then it is basically certain.

**Comment by ambition-consulting** [comment]
A workaround has been provided: https://github.com/swagger-api/swagger-ui/issues/5433#issuecomment-901628267

**Comment by ambition-consulting** [comment]
@wll8 Tried to make it work inside your try.js, but can't get it to receive the externalValue - I just receive undefined always on debugging.

Sample spec is provided in the comment above.

**Comment by wll8** [comment]
I will also participate together to help it work in redoc-try, can you provide links to reproducible problems online.

I get stuck in an infinite loop when I just use swagger.

![image](https://user-images.githubusercontent.com/28223260/130217289-c03df97d-8117-4536-aa9a-03ec686cb4eb.png)
![image](https://user-images.githubusercontent.com/28223260/130217351-674dabb6-04ab-437e-a597-c450272ac18b.png)
