### ISSUE TITLE
FailureURL scheme must be "http" or "https" for CORS request

### ISSUE THREAD

**Issue by ghost** [wll8/redoc-try#19]
I am testing this on my own API When I hit `Execute` and then I get the follow error. Any ideas what might be going on or could you provide any further debugging steps?

```
Failed to fetch.
Possible Reasons:CORSNetwork 
FailureURL scheme must be "http" or "https" for CORS request.
```

**Comment by wll8** [comment]
Open the browser console and you should get a more detailed error report.
I guess it may be because your interface is not configured for cross-domain.  Or, it is because you accessed the http interface from https. For cross-domain issues, the browser can't do anything about it.
