### ISSUE TITLE
Authorization

### ISSUE THREAD

**Issue by smeevil** [wll8/redoc-try#2]
Hi there,

I'm using your modifications with great success and really like the integration :)

The problem is, I've now added an authorization requirement to the API which means you need to provide an `Authorization: Bearer xxx` header.

In the default Swagger UI, it shows the following:

<img width="705" alt="CleanShot 2020-06-06 at 15 28 21@2x" src="https://user-images.githubusercontent.com/13874/83945360-683a1e00-a80a-11ea-9eae-048e185b51ce.png">

And when you click on it:

![CleanShot 2020-06-06 at 15 30 32@2x](https://user-images.githubusercontent.com/13874/83945415-c36c1080-a80a-11ea-8d4e-42c2bd498623.png)

After you have done this, the `try out now` will add the correct headers.

Would you have any suggestions on how to get this working in your solution as well?

Thanks in advance,
Gerard.

**Comment by wll8** [comment]
Thanks for the reminder. I am solving this problem. ^_^

**Comment by wll8** [comment]
[Add the `AUTHORIZE` button to `redoc`:](https://github.com/wll8/redoc-try/commit/a982952e24d8d346f98dd671c4f93e8753d92160)

![image](https://user-images.githubusercontent.com/28223260/83949356-e7087880-a855-11ea-8949-3a82e1229507.png)

**Comment by smeevil** [comment]
Awesome, so quick, thank you :)

I just made a small adjustment so you can pass along the configuration options to Redoc.init
see: https://github.com/smeevil/redoc-try/commit/42fa3991f9fc87873dc272bebd10286ca3fbbf14

**Comment by wll8** [comment]
Very good, very concise. I really hope to merge this modification.
