### ISSUE TITLE
problem in design

### ISSUE THREAD

**Issue by mkassir95** [wll8/redoc-try#23]
Hello
The download button hides the json response
![image](https://user-images.githubusercontent.com/72728047/163241175-086bd9fa-7d61-4a0d-b5b8-2ce833ce04e2.png)

**Comment by wll8** [comment]
This is swagger's own problem. You can visit link [httpbin](http://httpbin.org/) to verify the problem, but I will try to alleviate the problem.

The download button is only shown when the mouse is over the json.

**Comment by wll8** [comment]
see: [try.js:105-109](https://github.com/wll8/redoc-try/commit/ebb8bfb9628ab621f197ffb5c5eb2e1c73dc1e71#diff-119d8aa7f4acb36400625fac0dc39bfec0c4c98d897883290d3bfc03a4870ef6R105-R109)
