### ISSUE TITLE
Support openAPI relative path

### ISSUE THREAD

**Issue by sbilello** [wll8/redoc-try#24]
Hello!
Thanks for creating this project!

I was curious if we are able to extend the `openApi` param to support a relative file system url and not only a url.

Example: 
```
 openApi: `./swagger.json`
 ```

Does this tool supports both `openAPI 3` and `swagger 2.0` json specifications?

**Comment by wll8** [comment]
In theory, open api 3 and 2 can be supported, and relative paths are also supported (depending on your own deployment location).

However, I will give a definitive answer after testing later.

**Comment by wll8** [comment]
Compatible with `yaml/json/3.0/2.0`

- [👉 online ./test/openapi.3.yaml](https://wll8.github.io/redoc-try/index.html?openApi=./test/openapi.3.yaml)
- [👉 online ./test/swagger.2.json](https://wll8.github.io/redoc-try/index.html?openApi=./test/swagger.2.json)
- [👉 online https://httpbin.org/spec.json](https://wll8.github.io/redoc-try/index.html?openApi=https://httpbin.org/spec.json)

Relative paths are supported, but it looks like you need to deal with basePath in openApi (this part may not be what redoc-try should do https://github.com/swagger-api/swagger-ui/issues/5981)

**Comment by sbilello** [comment]
Thanks for checking!
```
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>redoc try demo</title>
</head>
<body>
  <div id="redoc-container"></div>
  <script src="https://cdn.jsdelivr.net/npm/redoc@2.0.0-rc.55/bundles/redoc.standalone.min.js"> </script>
  <script src="./dist/try.js"></script>
  <script>
    // initTry(`https://petstore.swagger.io/v2/swagger.json`)
    initTry({
      openApi: `./test/swagger.json`,
      redocOptions: {scrollYOffset: 50},
    })
  </script>
</body>
</html>
```
It works as parameter appended to the url. The above does not work. I am not super familiar with js.
Is there a way to remove the URL param exposure?

**Comment by wll8** [comment]
@sbilello  I created a project using your code above, please try if it helps.

👉 https://stackblitz.com/edit/redoc-try-issues-24?file=index.html

![image](https://user-images.githubusercontent.com/28223260/203457213-3f21835d-9ec8-468f-8d9a-93c41e1e7997.png)

**Comment by sbilello** [comment]
I see you are running a node.js server.
Which is the cli instruction?
I was just performing  open index.html
from the terminal.

Thanks 🙏

**Comment by wll8** [comment]
It uses [http-server](https://www.npmjs.com/package/http-server) instead of opening files directly via open.

When opening a file through the open command, the file:// protocol is used, which does not allow ajax to read the file. So it is recommended to use the http:// method.

see: https://stackoverflow.com/questions/39007243/cannot-open-local-file-chrome-not-allowed-to-load-local-resource

**Comment by sbilello** [comment]
Thank you for your response!

**Comment by wll8** [comment]
Maybe it works out of the box for simple http protocol on linux/mac

``` sh
# python<=2.3
python -c "import SimpleHTTPServer as s; s.test();" 8000
# python>=2.4
python -m SimpleHTTPServer 8000
# python 3.x
python -m http.server 8000
```

**Comment by sbilello** [comment]
Last question:
Is there a way to remove the url parameter openApi:.... override?
Thanks

**Comment by wll8** [comment]
https://wll8.github.io/redoc-try/index.html?openApi=./test/openapi.3.yaml

The parameters on the url are just for me to switch the demo parameters, in fact, you don't need it, there is no problem of overwriting.

It is recommended to refer to the code in this place:

https://stackblitz.com/edit/redoc-try-issues-24?file=index.html
