### ISSUE TITLE
Try it option only works with spec url, it doesn't work when openApi spec is given as json object 

### ISSUE THREAD

**Issue by shameel28** [wll8/redoc-try#25]

**Comment by wll8** [comment]
In the [v1.4.2](https://github.com/wll8/redoc-try/releases/tag/1.4.2) version, the openApi parameter supports json objects, [here is the code implementation](https://github.com/wll8/redoc-try/commit/27611da08b219d407f76d011ccc0e4041349cb1f#diff-119d8aa7f4acb36400625fac0dc39bfec0c4c98d897883290d3bfc03a4870ef6).

**Comment by wll8** [comment]
see [v1.4.2](https://github.com/wll8/redoc-try/commit/27611da08b219d407f76d011ccc0e4041349cb1f)

**Comment by shameel28** [comment]
Thanks
