### ISSUE TITLE
OpenAPI 3.1 support 

### ISSUE THREAD

**Issue by LeWolOnline** [wll8/redoc-try#35]
I am using your library and recently upgraded my file to OpenAPI 3.1. After that I started getting a warning:

> Unable to render this definition
> The provided definition does not specify a valid version field.
> Please indicate a valid Swagger or OpenAPI version field. Supported version fields are swagger: "2.0" and those that match openapi: 3.0.n (for example, openapi: 3.0.0).

Can you tell me if it is possible to enable/add support for version 3.1?

**Comment by wll8** [comment]
Because I tried openapi 3.1 and it works fine. So please provide the version of redoc-try you are using.

Also, it is recommended that you try the latest version:

https://github.com/wll8/redoc-try/releases/tag/1.4.9

**Comment by LeWolOnline** [comment]
I used version 1.4.8, which at that time was in the example in readme.md.
Yes, everything works on version 1.4.9, thanks.
