### ISSUE TITLE
Authorization doesn't have the expand icon to show auth details

### ISSUE THREAD

**Issue by shameel28** [wll8/redoc-try#36]
Authorization doesn't have the expand icon to show auth details like in redoc as shown in screen shot
<img width="1536" alt="Screenshot 2024-03-11 at 10 27 24 AM" src="https://github.com/wll8/redoc-try/assets/109072122/695264d0-eaff-4a38-ae74-d9e3364d44ac">

**Comment by wll8** [comment]
What version of redoc is this?

**Comment by wll8** [comment]
No more information, so closing this question.
