### ISSUE TITLE
Height type error

### ISSUE THREAD

**Issue by Os41** [wll8/redoc-try#37]
<img width="494" alt="Screenshot 2024-04-22 at 4 42 23 AM" src="https://github.com/wll8/redoc-try/assets/61876944/9f8b6116-2739-423a-9706-79c38f87716a">

This happened if there is no **comment** under the endpoint name title `<h2>`, and there is no **Request samples** `<h3>` under the reqBox,

Can we add a check for **Response samples** `<h3>`, if we could not find the Request? 

Like this to avoid the bug, 
`if($(requestSel).length && ($(requestSel).text().includes("Request") || $(requestSel).text().includes("Response")))`

**Comment by wll8** [comment]
https://github.com/wll8/redoc-try/commit/823d2cde4a2238114d9c6200437ffee9fbfd5ac1
