### ISSUE TITLE
Multiple Servers Selection Support

### ISSUE THREAD

**Issue by LeWolOnline** [wll8/redoc-try#39]
I am using your library to render an OpenAPI file with multiple servers defined. However, I can't find a way to select which server the requests should be sent to. In Swagger UI, this functionality is available.
![image](https://github.com/user-attachments/assets/9faad658-4bdd-4cbf-a28e-50153af8cdd6)

Could you please let me know if there is an option to choose the server, and if not, is there any plan to add support for this feature in the future?

Thank you!

**Comment by wll8** [comment]
This feature is expected to be added within two days.

**Comment by wll8** [comment]
This feature is available starting with version [1.4.10](https://cdn.jsdelivr.net/npm/redoc-try@1.4.10/dist/try.js).


![241011_173529](https://github.com/user-attachments/assets/2e51f68c-dec6-4fdd-95c5-71e9b0a59127)
