### ISSUE TITLE
How to use in redocstandalone in react component?

### ISSUE THREAD

**Issue by anupsingh-anup** [wll8/redoc-try#4]
Please can you give a easy way or example to use in the react component.

**Comment by wll8** [comment]
Maybe it's like using a dom-based third-party library in `react`.

**Comment by anupsingh-anup** [comment]
is it possible or not ? If yes please can you provide some example where i can directly use try it out option with redoc. i feel it will be useful for everyone.

**Comment by wll8** [comment]
Sorry, this may not be a good solution.

This is a sample code: `<RedocTry tryText="try out" />`.

- `react/16.13.1`
- `react-dom/16.13.1`


``` html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8" />
    <title>Hello World</title>
  </head>
  <body>
    <div id="root"></div>
    <script src="//cdnjs.cloudflare.com/ajax/libs/react/16.13.1/umd/react.development.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/react-dom/16.13.1/umd/react-dom.development.js"></script>
    <script src="//unpkg.com/@babel/standalone@7.9.4/babel.js"></script>
    <script type="text/babel">
      function RedocTry(userCfg) {
        const {
          useEffect
        } = React

        function loadJs(url, callback) {
          var script = document.createElement(`script`)
          script.type = `text/javascript`
          if (typeof callback !== `undefined`) {
            if (script.readyState) {
              script.onreadystatechange = function () {
                if (script.readyState === `loaded` || script.readyState === `complete`) {
                  script.onreadystatechange = null
                  callback()
                }
              }
            } else {
              script.onload = function () {
                callback()
              }
            }
          }
          script.src = url
          document.body.appendChild(script)
        }

        useEffect(() => {
          Promise.all([
            `https://cdn.jsdelivr.net/npm/redoc@2.0.0-rc.28/bundles/redoc.standalone.min.js`,
            `https://cdn.jsdelivr.net/gh/wll8/redoc-try@1.3.2/dist/try.js`
          ].map(item => {
            return new Promise(resolve => {
              loadJs(item, () => resolve(item))
            })
          })).then(() => {
            window.initTry(Object.keys(userCfg).length ? userCfg : `https://petstore.swagger.io/v2/swagger.json`)
          })
        })
        return <div id="redoc-container"></div>
      }

      ReactDOM.render(
        <div>
          <RedocTry tryText="try out" />
        </div>,
        document.getElementById('root')
      );
    </script>
  </body>
</html>

```

**Comment by anupsingh-anup** [comment]
Yes. it adding multiple times try-out and it shows blank screen on try-out. I'm trying to pass { redocOptions: { hideLoading: true }
its not working and break in middle.
Below are my some redoc options:
```
const redocOptions = {
  hideLoading: true,
  hideDownloadButton: true,
  scrollYOffset: 56,
  theme: {
    typography: {
      fontFamily: '"Metric", sans-serif',
      headings: {
        fontFamily: '"Metric", Arial, sans-serif'
      },
      optimizeSpeed: true
    },
    spacing: {
      sectionVertical: 10
    }
  }
};
```

**Comment by anupsingh-anup** [comment]
Please can you modify that code sample because it adding multiple times try-out . It would be a great help.

**Comment by wll8** [comment]
What does it mean to add multiple try-out?

Does it mean that there are multiple try-out buttons on the same interface?

If you mean this, then my test did not find this problem. Please provide an example of the smallest reproducible problem, thank you.

**Comment by wll8** [comment]
T_T...

Maybe I have found the problem and it is being solved...

**Comment by wll8** [comment]
I am very sorry for the problems I have brought before. I will definitely go through a complete test in the future.

``` jsx
ReactDOM.render(
  <div>
    <RedocTry tryText="try out" redocOptions={{
        hideLoading: true,
        hideDownloadButton: true,
        scrollYOffset: 56,
        theme: {
          typography: {
            fontFamily: '"Metric", sans-serif',
            headings: {
              fontFamily: '"Metric", Arial, sans-serif'
            },
            optimizeSpeed: true
          },
          spacing: {
            sectionVertical: 10
          }
        }
      }}
    />
  </div>,
  document.getElementById('root')
);
```

Reference modification record: [fix: `redocOptions` is not recognized correctly](https://github.com/wll8/redoc-try/commit/cb13ef836115157d4efbd19ca87c51bf4119df32)

**Comment by anupsingh-anup** [comment]
Yes it adds try-out button twice. 

![image](https://user-images.githubusercontent.com/57786405/85847141-93d67580-b7c4-11ea-8fa1-94ac902d6021.png)

i also see a error in console.
![image](https://user-images.githubusercontent.com/57786405/85848048-1c094a80-b7c6-11ea-9435-9225d664c2ec.png)

**Comment by anupsingh-anup** [comment]
![image](https://user-images.githubusercontent.com/57786405/85850432-668cc600-b7ca-11ea-98ba-d42722ebd10e.png)
it rendering multiple times and sometime it just show blank with one try-out.

**Comment by wll8** [comment]
[Please try this react sample code.](https://github.com/wll8/redoc-try/issues/4#issuecomment-649451914)

I want to know the system you are using and the browser version.

- operating system:
- browser and version:
- react version:
- redoc version:
- redoc-try version:
- It’s better to have code that can cause problems:

The following is the result of my operation, which can work normally.

![image](https://user-images.githubusercontent.com/28223260/85851154-c42c0d00-b7e0-11ea-9fb0-d7056ce675d3.png)

- operating system: win10 x64
- browser and version: chrome 80.0.3987.149 x86
- react version: 16.13.1 umd
- redoc version: redoc@2.0.0-rc.28
- redoc-try version: redoc-try@1.3.0
- It’s better to have code that can cause problems:

**Comment by anupsingh-anup** [comment]
Please try this [code]( https://codesandbox.io/s/react-example-s3n8l)
To reproduce issue:  refresh page multiple times

![image](https://user-images.githubusercontent.com/57786405/85870351-88964080-b7ea-11ea-9fd6-d130e2cec3c3.png)
you would see similar in the above image.
i feel it rendering multiple times. Please do the needful.

**Comment by anupsingh-anup** [comment]
**Issue two** 
open same sandbox in the new page with full screen .i.e  https://s3n8l.csb.app/
Redoc is Responsive **three-panel design** with menu/scrolling synchronization.
Please notice that right panel couldn't able to show entire information. it cut off  and doesn't have scrollbar feature to see Entire information. I'm attaching image.
![image](https://user-images.githubusercontent.com/57786405/85871341-e1b2a400-b7eb-11ea-9e02-54c9c9acf68b.png)

**Comment by wll8** [comment]
## Multiple try buttons
Thank you for the online code.

Sorry, through your online code, after performing multiple refresh operations, I still haven't seen multiple times of try.

However, I think that the initTry method is executed multiple times due to `react` rendering multiple times.

You can try to judge that there is already a try button on the page and then no longer run the initTry method.

## swagger Small resolution display is truncated
Although this is due to the swagger-ui itself, the container margin of redoc has taken up a part of the space, but I also hope to optimize it.

![image](https://user-images.githubusercontent.com/28223260/85885717-61099d00-b817-11ea-8d87-968187767117.png)

**Comment by anupsingh-anup** [comment]
Thanks man. I'm able to resolve rendering issue. Now looking forward for the truncated one.

**Comment by anupsingh-anup** [comment]
```
<RedocStandalone
        specUrl={`/entities/api/v1/spec/?productionServer=${browserLocationOrigin}`}
        options={redocOptions}
        onLoaded={() => {
          setLoading(false);
        }}
```
If you see the above code you have given example how to pass the specurl, options in redoc-try. Do you have any idea for **onLoaded** ? is there any way to pass **redoc onLoaded property** also ?

**Comment by wll8** [comment]
If you want to use every parameter, you can set redocOptions to an array, corresponding to:

`[specOrSpecUrl?, options?, element?, callback?]`


react example:
``` jsx
<div>
  <RedocTry tryText="try out" redocOptions={[
    `https://petstore.swagger.io/v2/swagger.json`, // specOrSpecUrl
    {}, // options
    undefined, // element
    error => console.log(`onLoaded`, error) // callback
  ]}
  />
</div>
```

**Comment by anupsingh-anup** [comment]
How can i override or change swagger ui styling changes ? is there an option to pass in **swaggeroptions** and override a classname?

**Comment by anupsingh-anup** [comment]
> If you want to use every parameter, you can set redocOptions to an array, corresponding to:
> 
> `[specOrSpecUrl?, options?, element?, callback?]`
> 
> react example:
> 
> ```js-jsx
> <div>
>   <RedocTry tryText="try out" redocOptions={[
>     `https://petstore.swagger.io/v2/swagger.json`, // specOrSpecUrl
>     {}, // options
>     undefined, // element
>     error => console.log(`onLoaded`, error) // callback
>   ]}
>   />
> </div>
> ```

if i pass in array it doesn't add try-out button

**Comment by wll8** [comment]
The only way is to directly override the css style within the scope of `#swagger-ui` directly.

Reference code and picture:

[try.js#L57](https://github.com/wll8/redoc-try/blob/d31d0c47f06e5b67ec25eb7580588e88a3599ce6/try.js#L57)
``` css
body .swagger-ui .wrapper {
  padding: 0;
}
```

![image](https://user-images.githubusercontent.com/28223260/85979622-70553a00-ba13-11ea-94cc-e775458256eb.png)

Welcome to contribute optimized css.

**Comment by anupsingh-anup** [comment]
How can i use try.js file from local instead of cdn ? what are files required if i do from local ?

```
useEffect(() => {
          Promise.all([
            `https://cdn.jsdelivr.net/npm/redoc@2.0.0-rc.28/bundles/redoc.standalone.min.js`,
            `https://cdn.jsdelivr.net/gh/wll8/redoc-try@1.3.0/try.js`
          ].map(item => {
            return new Promise(resolve => {
              loadJs(item, () => resolve(item))
            })
          })).then(() => {
            window.initTry(Object.keys(userCfg).length ? userCfg : `https://petstore.swagger.io/v2/swagger.json`)
          })
        })
        return <div id="redoc-container"></div>
      }
```

**Comment by anupsingh-anup** [comment]
Okay. i'm ready to contribute and before that i want to tell the reason behind my css change. Redoc already provides **Responses feature** and which again duplicating by swagger ui. i want to hide responses-wrapper class in swagger-ui.
if this change looks fine to you , i can create a PR and do this change.
![image](https://user-images.githubusercontent.com/57786405/85983008-6841ce00-ba04-11ea-8607-4f92e8fa409c.png)

**Comment by wll8** [comment]
> How can i use try.js file from local instead of cdn ? what are files required if i do from local ?

Download all the cdn files on the network to the local, and use the local path.

- https://cdn.jsdelivr.net/npm/redoc@2.0.0-rc.28/bundles/redoc.standalone.min.js
- https://cdn.jsdelivr.net/gh/wll8/redoc-try/dist/try.js
- https://cdn.jsdelivr.net/npm/jquery@3.2.1/dist/jquery.min.js
- https://cdn.jsdelivr.net/npm/jquery.scrollto@2.1.2/jquery.scrollTo.min.js
- https://unpkg.com/swagger-ui-dist@3.25.1/swagger-ui-bundle.js
- https://unpkg.com/swagger-ui-dist@3.25.1/swagger-ui.css

**Comment by wll8** [comment]
> if i pass in array it doesn't add try-out button

This is caused by the `callback function` in the array overwriting the `callback function` in try.js, which, I think, means you want to override it.

The function of try.js to initialize swagger is done in the callback function.

Reference code:
[try.js#L44](https://github.com/wll8/redoc-try/blob/d31d0c47f06e5b67ec25eb7580588e88a3599ce6/try.js#L44)

**Comment by anupsingh-anup** [comment]
If i use try.js file and modify as per my needs in local.  does it require license ?

**Comment by wll8** [comment]
[WTFPL License](https://github.com/wll8/redoc-try/issues/1)

**Comment by wll8** [comment]
This question was closed because no response was received. If there are other questions, welcome to open new `issues`.

**Comment by katriel18** [comment]
Hi, can Redoc's try it functionality be enabled somehow, since I'm using this as a component in react and need to make requests?

`
<RedocStandalone
  specUrl="http://petstore.swagger.io/v2/swagger.json"
  options={{
    nativeScrollbars: true,
    theme: { colors: { primary: { main: '#dd5522' } } },
  }}
/>
`

**Comment by wll8** [comment]
Is the entire feature enabled? Or trigger a test of a single API via an event?

Neither of the above two functions currently has a direct way.
