### ISSUE TITLE
Not compatible with Redoc v 2.0-rc.33 or above

### ISSUE THREAD

**Issue by saadshaukat-hello** [wll8/redoc-try#7]
Try it out does not work with Redoc v 2.0-rc.33 or above. The current Redoc version is rc-48. Any possibility you could make it compatible with the latest version?

**Comment by wll8** [comment]
This issue will be resolved in a future version.

**Comment by wll8** [comment]
Now it has supported the current latest version of redoc `2.0.0-rc.48`.

``` html
<body>
  <div id="redoc-container"></div>
  <script src="//cdn.jsdelivr.net/npm/redoc@2.0.0-rc.48/bundles/redoc.standalone.min.js"> </script>
  <script src="//cdn.jsdelivr.net/gh/wll8/redoc-try@1.3.4/dist/try.js"></script>
  <script>
    initTry(`https://petstore.swagger.io/v2/swagger.json`)
  </script>
</body>
```

thank you for your feedback. @saadshaukat-hello
